import {
  Award,
  Bell,
  Boxes,
  CalendarCheck,
  CalendarDays,
  CalendarRange,
  ChartNoAxesCombined,
  ClipboardList,
  Clock,
  CreditCard,
  DoorOpen,
  Files,
  Gift,
  HeartHandshake,
  Layers,
  LayoutDashboard,
  Megaphone,
  MessageSquare,
  Package,
  Percent,
  Receipt,
  Scissors,
  Settings,
  ShoppingBag,
  Star,
  Sun,
  Truck,
  UserRound,
  Users,
} from "lucide-react";
export const navigation = [
  {
    label: "WORKSPACE",
    items: [
      { label: "Overview", href: "/dashboard", icon: LayoutDashboard },
      { label: "Calendar", href: "/calendar", pro: true, icon: CalendarDays },
      { label: "Appointments", href: "/appointments", icon: CalendarCheck },
      { label: "Waitlist", href: "/waitlist", pro: true, icon: Clock },
    ],
  },
  {
    label: "PEOPLE",
    items: [
      { label: "Clients", href: "/clients", icon: Users },
      {
        label: "Memberships",
        href: "/memberships",
        pro: true,
        icon: HeartHandshake,
      },
      { label: "Loyalty", href: "/loyalty", pro: true, icon: Award },
      { label: "Staff", href: "/staff", pro: true, icon: UserRound },
      {
        label: "Team schedule",
        href: "/team/schedule",
        pro: true,
        icon: CalendarRange,
      },
      { label: "Time off", href: "/time-off", pro: true, icon: Sun },
      { label: "Commissions", href: "/commissions", pro: true, icon: Percent },
    ],
  },
  {
    label: "SERVICES & SALES",
    items: [
      { label: "Services", href: "/services", pro: true, icon: Scissors },
      { label: "Packages", href: "/packages", pro: true, icon: Layers },
      {
        label: "Rooms & resources",
        href: "/resources",
        pro: true,
        icon: DoorOpen,
      },
      { label: "Point of sale", href: "/pos", pro: true, icon: ShoppingBag },
      { label: "Invoices", href: "/invoices", pro: true, icon: Receipt },
      { label: "Payments", href: "/payments", pro: true, icon: CreditCard },
      { label: "Gift cards", href: "/gift-cards", pro: true, icon: Gift },
    ],
  },
  {
    label: "INVENTORY",
    items: [
      { label: "Products", href: "/products", pro: true, icon: Package },
      { label: "Stock overview", href: "/inventory", pro: true, icon: Boxes },
      {
        label: "Purchase orders",
        href: "/purchase-orders",
        pro: true,
        icon: ClipboardList,
      },
      { label: "Suppliers", href: "/suppliers", pro: true, icon: Truck },
    ],
  },
  {
    label: "GROW YOUR BUSINESS",
    items: [
      { label: "Reviews", href: "/reviews", pro: true, icon: Star },
      { label: "Campaigns", href: "/campaigns", pro: true, icon: Megaphone },
      {
        label: "Reports",
        href: "/reports",
        pro: true,
        icon: ChartNoAxesCombined,
      },
    ],
  },
  {
    label: "WORKSPACE TOOLS",
    items: [
      { label: "Messages", href: "/messages", pro: true, icon: MessageSquare },
      { label: "Notifications", href: "/notifications", pro: true, icon: Bell },
      { label: "Documents", href: "/documents", pro: true, icon: Files },
      {
        label: "Settings",
        href: "/settings/general",
        pro: true,
        icon: Settings,
      },
    ],
  },
];
